#index:
#    path: /
#    controller: App\Controller\DefaultController::index

equipement:
    path: /equipement/accueil
    controller: App\Controller\EquipementController::accueil

allequipement:
    path: /equipement/allequipement
    controller: App\Controller\AllEquipementController::allequipement